server:
  port : 8020

spring:
  application:
    name: ms-order

  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/